name = "skybox-proxy"
main = "src/index.js"
compatibility_date = "2025-04-01"

routes = [
  { pattern = "skybox.cataclyse.xyz/*", zone_name = "cataclyse.xyz" },
]

[assets]
directory = ".."
binding = "ASSETS"
exclude = [".git/**", ".wrangler/**", "worker/**", ".cataclyse/**"]
